### ISSUE TITLE
receiving issue

### ISSUE THREAD

**Issue by dendzos** [stratisproject/stratisX#23] opened 2017-06-04 10:53 UTC
Hi, I sent some stratis to my wallet yesterday and they didn't receive jet. Wallet is synced today. What should I do? Thanks. Best regards.

**Comment by graber5989** [comment] 2017-06-04 19:38
I have the same problem here, sent my stratis by bittrex yesterday and today the wallet is synced but i have no stratis in it.

**Comment by dangershony** [comment] 2017-06-04 19:59
Can you see the trx on the blockchain?

**Comment by graber5989** [comment] 2017-06-04 20:05
if i put it in the stratis blockchain explorer i find the transaction and under "redeemed in" it tells me "not yet redeemed". Is that of any concern?

**Comment by photigy** [comment] 2017-06-04 20:07
Same Issue here. have sent STRAT to my local STRAT wallet using changelly and have never received it. Have a transition on changelly marked as OK and have nothing on a wallet.  Any ideas where is it?

**Comment by photigy** [comment] 2017-06-04 20:14
Ok, looks like the output transaction on changelly can't be found in blockchain explorer. 
How it can be? Talking to guys from changelly.com

**Comment by graber5989** [comment] 2017-06-04 20:27
as it seems my transaction is confirmed at the blockchain but the wallet hasnt received coins, even if the wallet is synced and has the current blockchain, the adress is correct too (SMN3CmMqXBohSPvtKuZu5NM2B2caTBU7Sb). 
This is the tx id if it helps: 
d5f88e4ac90fe3b222dedd99845ef5f3cddfcc5cab3465ff0281ca55367ab599

**Comment by 0xhjohnson** [comment] 2017-06-04 20:31
Changelly seems to be taking a long time. 3 hours minimum

**Comment by photigy** [comment] 2017-06-04 21:14
It was already 10+ hours. Still can't find a transaction in blockchain (OUTPUT TRANSACTION HASH	e517f650cbe41ee7c1589d82a6b4736a8099d22d981ea61d5776e3458deaef05 )
Must be something weird on their side?

**Comment by 0xhjohnson** [comment] 2017-06-04 21:23
Yeah must be something on their end. All you can do is talk to Changelly support

**Comment by cocotton** [comment] 2017-06-05 00:51
Guys, your wallet may say it's synqued, but it might not be.

Right now, mine says "Processed 390548 blocks of transaction history", yet when I take a look at the stratis blockchain, it looks like we're at block 391731.

My wallet seems to by synching really slowly.

**Comment by Ganeshaji** [comment] 2017-06-05 02:02
I hope cocotton is right. I see the same thing. I think the wallet is taking a delayed time to sync. Someday in the future we will all look back and laugh that transactions took this long....well till that day comes, fingers crossed.

**Comment by cocotton** [comment] 2017-06-05 02:52
Alright, it seems my assumption were right!

The wallet that does not synq up was installed on Windows. What I did now is install the wallet on my OSX laptop, wait for it to fully synq, then restored by backed up wallet from Windows and voilà! 

I see my STRATs now :)

**Comment by dendzos** [comment] 2017-06-05 09:20
I already have installed wallet on my OSX, should I uninstall it then do installation on it again? Thanks. :)

**Comment by cocotton** [comment] 2017-06-05 14:14
@dendzos if you do, make sure you backup your wallet first!

**Comment by dev0tion** [comment] 2017-06-05 21:07
Looks like there were (are?) some issues on changelly's end yes.

If you guys still have issues:
- Close your wallet
- In the next steps, whatever you do do NOT delete the wallet.dat file!
- On Windows: navigate to %appdata%/Stratis and delete everything EXCEPT wallet.dat
- On OS X: navigate to ~/Library/Application Support/Stratis and delete everything EXCEPT wallet.dat
- Start your wallet

**Comment by nickothman** [comment] 2017-06-06 10:53
Hi Dev,
After I've navigated to %appdata%/Stratis, I have the following folders on screen:
.lock
blk0001
db
debug
**wallet (Winmail.dat File (.dat)) - Is this the wallet .dat you are talking about?**

Thanks
Regards
Nick

**Comment by dev0tion** [comment] 2017-06-06 10:55
Hey @nickothman,
That is the wallet.dat file I'm talking about indeed. Do NOT remove that, but remove everything else and start your wallet again.

**Comment by nickothman** [comment] 2017-06-06 11:01
Thanks, I'll give a go

Nick

**Comment by dendzos** [comment] 2017-06-06 12:08
Hi, Dev. How can I add nodes to my Mac, I put in Stratis folder file with nodes but nothing is change, still only 1 connection. What app should I use to create file with nodes, maybe I use wrong app (iNotepad) ? 

Thanks. Regards.

**Comment by nickothman** [comment] 2017-06-06 18:44
Hi, 
I followed your instructions... done a restart and still showing 42 weeks behind according to the gauge at the bottom of the screen.. what to do next? wait?
Thanks
Regards
Nick

**Comment by dev0tion** [comment] 2017-06-07 08:14
@dendzos you can use these instructions to create the stratis.conf file on a Mac.
![26853414-84bfedca-4b1a-11e7-8172-e29833c8213c](https://user-images.githubusercontent.com/10409230/26868616-e68b5ac2-4b69-11e7-980f-551a023fa4c5.png)

You can get a node list here: https://chainz.cryptoid.info/strat/#!network
Click "node list"  behind v2.0.0.2.

We will be releasing a new version of the client that solves these problems.
Sorry for the inconvenience.

**Comment by nickothman** [comment] 2017-06-07 09:10
Morning,
So, where that leaves me? I spent $100 worth in Strats a couple of days ago and I don't have them in my wallet.. What are my options?

Thanks for your help
Regards
Nick

**Comment by Ganeshaji** [comment] 2017-06-07 09:23
Me too, I spent 150 USD last week and still don't have on my wallet.

**Comment by dendzos** [comment] 2017-06-07 11:22
@dev0tion Thank you very much. I did it, all my Strats are in my wallet now. 

Thanks again, 
Best regards.

**Comment by nickothman** [comment] 2017-06-07 13:05
@devOtion, do ytou have instructions to create the stratis.conf file on window?

Thanks
Regards
Nick.

**Comment by cocotton** [comment] 2017-06-07 14:12
@nickothman you can use any text editor you want to create the file.

The content of the file should be the same as the one you'll get [here](https://chainz.cryptoid.info/strat/#!network) (click on `node list` next to "/Stratis:2.0.0.2/" in the Sub-version section)

Save your file **and make sure it has a .conf extension (it should NOT end with .txt)**. You can validate this by right clicking on the file and then clicking on properties.

Make sure to restart stop and start the wallet once this is done.

Hope this helps!

**Comment by donnolovido** [comment] 2017-06-07 15:26
I have made a transaction from my stratis wallet to another wallet at the 3th of june and still it hasn't been confirmed.. 
Can't find the ~/Library/Application Support/Stratis in my macbook..
I really don't know what to do now, I've had some e-mail contact but in the last mail they say:
Hi,
 
Then you Stratis folder is not there.
 
Regards
 
Stratis team
????? totally worthless respond.
Tried to send 250 euro worth of stratis and i am afraid it is lost..

**Comment by dev0tion** [comment] 2017-06-07 15:29
@nickothman what @Cocotton said. Just place that file in the %appdata%/Stratis folder and restart your wallet.

@donnolovido are you running the Stratis Qt wallet or Electrum wallet?

**Comment by donnolovido** [comment] 2017-06-07 15:30
@dev0tion 
I am running the Stratis Qt wallet

**Comment by dev0tion** [comment] 2017-06-07 15:33
@donnolovido then you're probably looking for the Stratis folder just by using finder, but it's hidden so you can't find it that way.
Open Finder, in the menu click Go then Go to Location and enter:
~/Library/Application Support/Stratis

That should get you in the folder :). 
If your wallet has no connections, follow the steps above to create a stratis.conf file containing nodes.
If your wallet says it's synced (or partially synced), but you don't see your incoming transactions you will have to resync the blockchain. Steps for this:
- Close your wallet
- For Windows: navigate to %appdata%/Stratis using the address bar in Windows Explorer
- For OS X: navigate to ~/Library/Application Support/Stratis using Finder (Go menu -> Go to Location)
- In that folder DO NOT remove the wallet.dat file, as that contains all your funds
- Remove all the other files in the folder (again, NOT wallet.dat)
- Start your wallet and you should be good to go

**Comment by donnolovido** [comment] 2017-06-07 15:35
@dev0tion I have tried to search ~/Library/Application Support/Stratis in my finder and almost everywhere in my Macbook but it isn't there..

**Comment by donnolovido** [comment] 2017-06-07 15:38
@dev0tion I found it! it was hidden haha, thank you mate! i will try it now

**Comment by nickothman** [comment] 2017-06-07 16:06
ok I'll give it go

**Comment by photigy** [comment] 2017-06-07 18:31
Guys, where is the " %appdata%/Stratis folder " on macOS? I can't find it to place statis.coft inside. Is it the same as  ~/Library/Application Support/Stratis?
Confused..

**Comment by photigy** [comment] 2017-06-07 18:47
One more question to the community: is there is a way to do something with changelly.com, if they recorded a transaction that actually does not exists in blockchain explorer, and do not respond on support tickets? Money is gone.
What possible ways to make them investigate this and put things back to my account?
I was buying STRAT and it never came to my strat wallet, and the transaction from it does not exist in blockchain... Any advice? 
thanks!

**Comment by cocotton** [comment] 2017-06-07 19:01
@photigy if you are on Mac OS X, you can try to open the console and run the following command

```
find ~ -name 'wallet.dat'
```

This will return the path where you stratis wallet is and also the directory where you should place your stratis.conf file (not .coft)

**Comment by dev0tion** [comment] 2017-06-07 19:22
@photigy pretty much all exchanges are absolutely swamped with tickets, they will get back to you.
If the transaction does not show up on the explorer they will have to resync their node and send it again, they will respond to your support ticket, but it may be a while.

@nickothman did it work?

**Comment by dev0tion** [comment] 2017-06-10 00:25
Hey guys, 

Please find the new version of our wallet here: https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.3

Follow the steps to solve your issues. If you have any issues please let us know.

**Closed as completed** 2017-06-10 10:18 UTC
